### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "position". Expected String, got Array.

### ISSUE THREAD

**Issue by Bakuutin** [euvl/vue-notification#10]
In your props list you have position:
```js
position: {
      type: String,
      default: defaults.position
}
```
It declared to be string, but in `defaults.js` default position is `['top', 'right']`

To fix this warning you can either change type of prop or set default position to `'top right'`.

Thanks.

**Comment by euvl** [comment]
Hey @Bakuutin , 

Thanks a lot for spotting this one, I think i've accidently removed `[String, Array]` type when merging last pull request, will fix asap !

**Comment by euvl** [comment]
@Bakuutin @Melse , version 1.3.1 should have a bugfix. 
Let me know the fix works for you.

Thanks for reporting the issue 👍

**Comment by Bakuutin** [comment]
Thanks! :slightly_smiling_face:
