### ISSUE TITLE
ESLint: Component name "notifications" is not PascalCase.

### ISSUE THREAD

**Issue by karakayasemi** [euvl/vue-notification#105]
Eslint is warning with this message: `ESLint: Component name "notifications" is not PascalCase.`. When I use Pascal case `vue-notification` is not working.

**Comment by onrc** [comment]
#102 merged 10 days ago but npm registry isn't up-to-date. You can use github url in your package.json.
```json
"dependencies": {
  "vue-notification": "https://github.com/euvl/vue-notification.git"
}
```

**Comment by euvl** [comment]
published
