### ISSUE TITLE
Boxy theme repo deleted

### ISSUE THREAD

**Issue by anupamsr** [euvl/vue-notification#106]
Hi,

Sorry to bug you like this, but I didn't see any other way to contact you. I have been an avid user and a fan of your Boxy Theme (https://packagecontrol.io/packages/Boxy%20Theme). Have you deleted the repository, though? It doesn't seem to work anymore :(

**Comment by anupamsr** [comment]
Boxy theme is deprecated in favor of DA UI.

**Comment by anupamsr** [comment]
It seems DA UI and A File Icon are also gone

**Comment by euvl** [comment]
Not sure what is going on, but i do not have connection to that theme
