### ISSUE TITLE
It's a bad practice to use single-word component name

### ISSUE THREAD

**Issue by ramiy** [euvl/vue-notification#107]
Only HTML elements should use single word. Custom components should use multi-word names.

For more information see Vue.JS **Style Guide**:

https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential

Also, ESLint warns about this `ESLint: Component name "notifications" is not PascalCase.`.

See more info **Vue.js ESLint plugin**:

https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/component-name-in-template-casing.md

**Comment by ramiy** [comment]
I see you already fixed that in #102 ! :-)

Awesome Plugin!!!

**Comment by euvl** [comment]
Thanks
