### ISSUE TITLE
[Vue warn]: The client-side rendered virtual DOM tree 

### ISSUE THREAD

**Issue by justyeh** [euvl/vue-notification#11]
In my  ssr project , there is a warming :

`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

**Comment by euvl** [comment]
I didn't test it with ssr, so cant guarantee it working. 
Will take look, thanks 👍

**Comment by joshua1** [comment]
@justyeh Are you using this with nuxt.js?  doesn't seem to work with the 1.0 rc release

**Comment by justyeh** [comment]
yeh , I have used it, bu it doesn't work with SSR



justyeh@163.com
 
From: joshua Oguche
Date: 2017-08-21 17:08
To: euvl/vue-notification
CC: justyeh; Mention
Subject: Re: [euvl/vue-notification] [Vue warn]: The client-side rendered virtual DOM tree (#11)
@justyeh Are you using this with nuxt.js? doesn't seem to work with the 1.0 rc release

**Comment by euvl** [comment]
Hey @joshua1, @justyeh, 

Completely forgot about this issue 😭 I have not looked into it yet. If anyone has a bit of free time to make a review of what might be causing problems - i will be very-very happy to review a PR 😄

**Comment by lyquocnam** [comment]
waiting for this 👍

**Comment by traxxxl** [comment]
Hi!  
it doesn't work with SSR yet

**Comment by jhesgodi** [comment]
FYI for people using Nuxt and want to render this component only on client-side:

First, create a plugin `/plugins/vue-notification.js`
```javascript
import Vue from 'vue'
import Notifications from 'vue-notification'

Vue.use(Notifications)
```
Then, add it to your `nuxt.config.js`
```javascript
...
  plugins: [
     ...
    { src: '@/plugins/vue-notifications', ssr: false }
     ...
  ],
...
```
Finally, at the`layout` or vue app file, add the `notification` component inside a `no-ssr` tag
```vue
<template>
  <div>
    <no-ssr>
      <notifications/>
    </no-ssr>
    <nuxt/>
  </div>
</template>
```

**Comment by dioxine** [comment]
Thanks! Exactly that <no-ssr> tag disable this nasty notification! Works on vue-carousel as well too!

**Comment by euvl** [comment]
SSR file added to dist/ssr.js
