### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by karakayasemi** [euvl/vue-notification#110]
Hey @euvl ,
Firstly, thanks for all your efforts. I wonder when will you release `Allow disabling of notification close on click` feature. 
Regards
Semih

**Comment by Splashdown** [comment]
Hey,

Really nice work, i got the same question, when will you release ` Allow disabling of notification close on click` feature.
Would be a great new feature.

Thank you so much

**Comment by karakayasemi** [comment]
Closing this in favor of 1.3.16.
