### ISSUE TITLE
How can I trigger notification from template?

### ISSUE THREAD

**Issue by cichy380** [euvl/vue-notification#111]
Hi, 

my website is not a SPA aplication. Vue only help my in some.. elements. But notifications I want to created based on _vue-notification_ (good job!) and I want to using it on all my website.

If I want to do this I need to fired notification directly from template. Just like that:
```
<html>
<body>
   <div id="app">
      <notifications text="Welcome! This is text notification triggered after page loaded"></notifications>
   </div>

   <script src="vue.js">
   <script src="app.js">
</body>
</html>
```

Is it possible?

**Comment by VladStepanov** [comment]
In vue.js make window instance of Vue 
```
vue.js
window.vue = new Vue
```
And in app.js just trigger from window
```
app.js
const vm = window.vue

vm.$notify()
```
