### ISSUE TITLE
Programmatic closing of notifications?

### ISSUE THREAD

**Issue by jamesmorgan** [euvl/vue-notification#115]
Is there anyway to programmatically close an open notification? Maybe by ID or reference. 

Cheers

James

**Comment by Loremaster** [comment]
Bump. Having the same issue where I want to show notification forever unless the error would occur. Need a way to close existing popup

**Comment by emko4** [comment]
I see, that this functionality is in new commits. Is it planned to release a new version soon?

**Comment by euvl** [comment]
Released yesterday, let me know if it does not work 👍

**Comment by emko4** [comment]
@Zellotath you are right 👍

**Comment by euvl** [comment]
@emko4 merged, published vue-notification@1.3.20

**Comment by dikkini** [comment]
Can you add in README.md information about "How to close notification programmatically"? I did not find it.

**Comment by abrichr** [comment]
@dikkini this seems to work:

```
const id = new Date().getTime();  // this can be any number
Vue.notify({
  id,
  text: 'This annotation will be removed immediately'
});
Vue.notify.close(id);
```

**Comment by maxKimoby** [comment]
Please add this to the README, I had to search forever to figure out.
