### ISSUE TITLE
How to use it from a CDN?

### ISSUE THREAD

**Issue by akarelas-pt** [euvl/vue-notification#116]
**Is your feature request related to a problem? Please describe.**
I am trying to use your library in a project where I'm not allowed to use npm, but only CDNs. I cannot do that, despite trying various ways to do it. Contrary to what most vue modules/plugins do, this module doesn't contain instructions on how to achieve this (usage from CDN).

**Describe the solution you'd like**
I would like for instructions to be written for how to use the module from CDN (i.e. without compiling it with npm)

**Comment by leafchild0** [comment]
Any updates on this yet? Need such an ability as well

**Comment by leafchild0** [comment]
This should help: https://github.com/euvl/vue-notification/issues/31
