### ISSUE TITLE
Is there a way to set a kind of bottom offset position? 

### ISSUE THREAD

**Issue by luchorengo** [euvl/vue-notification#117]
Since my app uses a fixed footer at bottom page which includes form button actions, when notification is shown as "bottom right" position it overlaps those buttons.
Is there a way to set a kind of bottom offset position? I've tried by adding a custom class with margin-bottom in the notification div, but when several notifications are shown, the margin is applied to every element.

Any suggest will be appreciated.

Thanks in advance

![screenshot from 2019-02-16 02-22-33](https://user-images.githubusercontent.com/12195864/52894987-16dbca80-3192-11e9-9d9b-cce3ce696e9a.png)

![screenshot from 2019-02-16 02-22-53](https://user-images.githubusercontent.com/12195864/52894988-193e2480-3192-11e9-84ef-bac6d2311016.png)

**Comment by euvl** [comment]
I'm afraid there is no way (check source code tho i might be wrong)

**Comment by dennis-ec** [comment]
I also would love an functionality like that. My current work around is to set the margin in css and limit max property to 1.

**Comment by shoejep** [comment]
I found I wanted the thing but with an offset from the top. I haven't tested it extensively but this worked well enough for me.

`.notification-wrapper {
        position: relative;
        top: 60px;
    }`

**Comment by nidilasi** [comment]
Hi, I had the same problem and solved it with this CSS:
   ```
 .notifications >>> .notification-wrapper:last-child {
        margin-bottom: 30px;
    }
```

The 'notifications'-css class it applied to the div where the notifications will be shown.

**Comment by peercode-eric** [comment]
For people search for a better solution I used:
`this.$notify.default({
          msg: msg,
        }).then(function(notify){
          notify.styles.marginBottom = ($(".bottomscreen").height()+20)+"px";
        })
      }`

This will add a margin bottom based on the actual height of the element, in my case an element with class bottomscreen.

Hope it helps someone
