### ISSUE TITLE
Unterminated regular expression error on dist/index.js

### ISSUE THREAD

**Issue by enrtama** [euvl/vue-notification#121]
**Describe the bug**
When I add "vue-notification" to my dependencies and build my project I get the error
Bundler used: Parcel bundler

**To Reproduce**
1. Add "vue-notification" to your dependencies
2. Build with parcel-bundler
3. See error

**Expected behavior**
Successful build

**Screenshots**
`node_modules/vue-notification/dist/index.js:1070:85: Unterminated regular expression (1070:85)
  1068 |     css += '\n/*# sourceURL=' + sourceMap.sources[0] + ' */'
  1069 |     // http://stackoverflow.com/a/26603875
> 1070 |     css += '\n + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + ' */'
       |                                                                                     ^
  1071 |   }`

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Command line interface
 - Version: latest
 - Node version: 8

**Comment by euvl** [comment]
It is not a bug in the plugin. from your code line 1070,
```
 ccc = '\n + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + ' */'
```
is not valid code, it should be something like

```
 css = '\n' + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + ' */'
```

**Comment by enrtama** [comment]
Thank you for the quick reply, probably it's _parcel bundler_
