### ISSUE TITLE
Injection cause default style to overrides custom style

### ISSUE THREAD

**Issue by LeBenLeBen** [euvl/vue-notification#122]
**Describe the bug**
The plugin default styling is injected by the JavaScript on page load. It is outputed right before `</head>` which is usually after any custom CSS you might have loaded already.

This is an issue because it prevents some custom styling property to be applied correctly.

Note that this issue is usually visible only when bundling for production as in development style are injected as well and in this case respect the order.

**To Reproduce**
For example with a bare Vue CLI project, within the `main.js` file.

1. Load the plugin normally and then your custom style:
```js
import Vue from 'vue';
import Notifications from 'vue-notification';

Vue.use(Notifications);

import './assets/scss/main.scss';
```

`main.scss` includes some custom style such as:
```scss
.vue-notification.success {
    color: #184e2c;
    background-color: #d8f3e2;
    border-left-color: #89dca7;
}
```

2. Build for production and open the app in the browser

👉 The custom style is overrided by the default style because Vue notification style is injected after, like this:

```html
<head>
  <link href="/css/app.e49bda02.css" rel="stylesheet">
  <style type="text/css">
    .notifications{display:block;position:fixed;z-index:5000}.notification-wrapper{display:block;overflow:hidden;width:100%;margin:0;padding:0}
    …
  </style>
</head>
```

**Expected behavior**
The custom style, loaded after in the bundle, should not be overrided by the default style.

A solution for this would be for the plugin to provide an external CSS file that users can optionally load. This would allow them to completely avoid loading the default style if they want to as well as loading it at the right time and including it properly in their main stylesheet.

**Notes**
I've seen the option to change the default classes which would kinda solve the issue, but since I use most of the default style, I would rather avoid that. Also the default style would still be present and loaded whereas not being used.

**Comment by treykaws** [comment]
I am experiencing similar issues with customizing the styles of the notifications. If I make even minor tweaks to the default styles, they are not being picked up.

Has anyone figured out how to isolate and resolve this issue?

**Comment by nidilasi** [comment]
I have no problems with default/custom styles. I once had different results in production and solved it by moving the import lines in `main.js`.
Here's my order of imports:
```
import Vue from 'vue'

import store from './store/store.js'

import Notifications from 'vue-notification'
import router from './router' // inside router a component with the custom styling gets loaded
import App from './App'
```

**Comment by LeBenLeBen** [comment]
My import order is already the same as yours, i.e. notifications before the app. The problem still occurs in all projects (using Vue CLI) for me. The only solution I found for now is to `!important` all the rules that are already defined by the plugin.

**Comment by hmaesta** [comment]
API should have an option `load_default_css: false`
