### ISSUE TITLE
AdBlock hide notification show

### ISSUE THREAD

**Issue by odo48** [euvl/vue-notification#127]
**Describe the bug**
Not showing the notification if AdBlocker installed.

**To Reproduce**
1. Add adBlocker ( I use this one https://chrome.google.com/webstore/detail/adblocker-for-chrome-noad/alplpnakfeabeiebipdmaenpmbgknjce?utm_source=extension&utm_medium=browser_action&utm_campaign=homepage_clicked)
2. Try to make a notification to show
3. Nothing happens

**Expected behavior**
I expect to see the notification

**Desktop (please complete the following information):**
- any device with adblocker

**Additional context**
The problem is class names. The AdBlocker trigger names like: ad, ads, facebook, twitter, notification etc

**Comment by euvl** [comment]
Was not able to replicate. I think it depends on the content within notification itself
