### ISSUE TITLE
Make the transition of the animation custom

### ISSUE THREAD

**Issue by ronilitman** [euvl/vue-notification#129]
**Is your feature request related to a problem? Please describe.**
I am not able to set my own transition properties

**Describe the solution you'd like**
pass a prop that disables the default transition

**Additional context**
When I pass a speed prop, for example 600, I get inlined style that looks like `transition all 600ms....`. The thing is that I want to have different transitions for different style properties, and it looks like I can't do that right now. The workaround that I found is passing NaN to speed prop, but I don't think that's a good long term solution..

Thank you!

**Comment by mishokupatadze** [comment]
Use speed property for that

**Comment by ronilitman** [comment]
In the additional context section I explained why using speed prop is not enough for me.
