### ISSUE TITLE
IgnoreDuplicates prop is not used

### ISSUE THREAD

**Issue by neeilya** [euvl/vue-notification#132]
**Describe the bug**
IgnoreDuplicates param does not have an effect.

**To Reproduce**
1. Fire same notification twice with `ignoreDuplicates: true` flag

**Expected behavior**
Only one notification should appear.

**Comment by reepush** [comment]
@neeilya it's already there, @euvl needs to update a package on npm.
You can pull a latest version from github directly this way:
```
npm i @euvl/vue-notification
```

**Comment by neeilya** [comment]
@reepush, no, the latest code in repo contains a bug which has been fixed in this pull request:
https://github.com/euvl/vue-notification/pull/138

Look how `ignoreDuplicates` component prop was always used ignoring the param coming from `Vue.notify` function.

**Comment by talberkoSB** [comment]
@euvl - can you please update the npm package to use the latest version?

**Comment by zelvik** [comment]
@euvl 
Could you update npm packge in npmjs repository, please?

Thank you

**Comment by jjatczak** [comment]
Can your create new release with the latest changes from master branch?
I am still waiting for this fix.

**Comment by zelvik** [comment]
I would recommend you to use https://www.npmjs.com/package/@remotehq/vue-notification where is last version. It is just fork of this repository.
