### ISSUE TITLE
Latest WebPack build and Vue-Loader casues 'Failed to mount component: template or render function not defined.' error

### ISSUE THREAD

**Issue by DelfsEngineering** [euvl/vue-notification#134]
The latest versions of Vue-Loader and WepPack need components to have a default export.

Using the following highlight from my code:
```
// package.json
...
    "webpack": "^4.35.0",
    "vue-loader": "^15.7.0",

//my vue component
    import Notifications from 'vue-notification'
    Vue.use(Notifications)
...
   import { EventBus } from 'Js/eventBus';
    export default  {
       ...
        name: 'toaster',
        components: {
            Notifications
        },
```
Throws this error:
`vue.esm.js?a026:628 [Vue warn]: Failed to mount component: template or render function not defined.`

Typically this happens when the component does not have a default export 
`    export default  {...` 
or there is a `require` with out specifying `default`

**Expected behavior**
No error like all other components

**Additional context**

Any suggestions as I'd think this would come up with many people ...

**Comment by DelfsEngineering** [comment]
Very odd, renaming the component as follows seems to have solved the issue. Perhaps a conflict internally?

`import Notifications1 from 'vue-notification'` // and all other references to `Notifications`

**Comment by euvl** [comment]
Weird, I don't think there's any browser api called "notifications"...also seems to work for me. I will update readme to suggest calling it "vuenotifications" or smth
