### ISSUE TITLE
Notification is not shown when using plugin as CDN

### ISSUE THREAD

**Issue by leafchild0** [euvl/vue-notification#137]
**Describe the bug**
When using a plugin as CDN or simply built as one file in HTML (manually), notifications are not shown. Due to the webpack bundle event 'add' is thrown but no one is listening, seems to be either a configuration or build issue. Adding a simple example below.

**To Reproduce**
1. Perform a build
2. Add a simple HTML  with any element (example below)
3. Add some logic to show a notification (example below)
4. Observe that nothing happens

**Code**
```<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=1024, initial-scale=1.0">
	<title>Test</title>

	<script src="https://unpkg.com/vue"></script>
<script type="text/javascript">
	window.vue = window.Vue; // quick fix for vue-notification
  </script>
  <script type="text/javascript" src="index.js"></script>
  <script type="text/javascript">
	window.vueNotification = window["vue-notification"].default;
	Vue.use(vueNotification);
  </script>
</head>
<body>
	<div class="test" id="test" @click="showNotif">Click me</div>
	<script>
		new Vue({
			el: '#test',
			methods: {
				showNotif: function() {
					Vue.notify({
						title: 'Important message',
						text: 'Hello user! This is a notification!'
					});
				}
			},
		});
		</script>
</body>
</html>
```

**Expected behavior**
Notification should be shown

**Desktop**
 - OS: Mac/Windows
 - Browser: ALL
 - Version: 1.3.16

**Additional context**
Again, this might be a configuration issue. Any comments appreciated.

**Comment by euvl** [comment]
You need to put <notifications/> in your template. please take a look into the documentation..

**Comment by leafchild0** [comment]
I did, it's automatically used when creating a bug, tho there is no section for code examples, I've changed template a bit

**Comment by euvl** [comment]
Oh sorry, Github didn't render "`<notifications/>`" word because it thought it is a part of markdown:DDD.
