### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by RomkaLTU** [euvl/vue-notification#139]
**Describe the bug**
This plugin doesn't work at all. 

**To Reproduce**
1. install with given instructions
npm install --save vue-notification
In main.js:
```
import Notifications from 'vue-notification'
Vue.use(Notifications)
```

Anywhere in component try to trigger notification:

```
this.$notify({
  group: 'foo',
  type: 'error',
  title: 'Error',
  text: 'Lorem ipsum...',
});
```
Nothing happens. No errors nothing.

**Expected behavior**
Notifications shows

**Additional context**
Using vue-cli 3

**Comment by vuphuctho** [comment]
https://github.com/euvl/vue-notification#how-to

> In App.vue:
> 
> `<notifications group="foo" />`

Have you added the component `notification` anywhere in your app?

**Comment by maestroDever** [comment]
Same here.
Followed all instructions and yet it shows nothing. Tested with latest version of vue.
vue-cli 3
vue 2.6.10

**Comment by euvl** [comment]
Did you find the solution to your issue?

**Comment by biodunbamigboye** [comment]
> https://github.com/euvl/vue-notification#how-to
> 
> > In App.vue:
> > `<notifications group="foo" />`
> 
> Have you added the component `notification` anywhere in your app?

This resolves it for me.
