### ISSUE TITLE
Issue with TypeScript --> type declaration missing

### ISSUE THREAD

**Issue by gnumarcelo** [euvl/vue-notification#14]
Hi, first of all, thanks for creating such a great notification plugin!

I'm trying to use your plugin in a Vuejs + TypeScript project and I've found an issue due to how the Typescript type declaration works (as you can see in the link below). I've also found a way to make this work in my project but I think it worth you to fix this in your lib code so that vuejs+ts newcomers will find it easier to use.

Cheers!

https://github.com/vuejs/vue-class-component/issues/128

**Comment by euvl** [comment]
Hey @gnumarcelo thanks a lot for a feedback!

Do you have any ideas how i could fix it? 
Because I feel a bit lost tbh (i did not use TS before). 

Thanks

**Comment by gnumarcelo** [comment]
@euvl see what I did in my boot.ts file:

![image](https://user-images.githubusercontent.com/6064/28527901-70bec892-7062-11e7-9bc0-bdbc34a5f039.png)

Maybe you could just add this Type Declaration inside of the module you export the`Notifications`.

**Comment by euvl** [comment]
But isn't it TypeScript syntax? 
Could you paste how does it look when transpiled to javascript?

**Comment by euvl** [comment]
Ok, so i will be happy to make a fix that does not require using ts features. Will be thankful to hear any ideas.

**Comment by euvl** [comment]
I've added type declaration to the documentation, will keep a fag "help wanted"
