### ISSUE TITLE
Nuxt.js ssr no styles

### ISSUE THREAD

**Issue by IngvarListard** [euvl/vue-notification#140]
**Describe the bug**
There is no styles for notifications for any props or even custom body element inside if the plugin imports from `'vue-notification/dist/ssr.js'` and with SSR mode. 
With SPA mode and direct import works fine.

**To Reproduce**
Installed `vue-notification` as  instruction says:
```javascript
// plugins/vue-notification
import Vue from 'vue'
import Notifications from 'vue-notification/dist/ssr.js'
// import Notifications from 'vue-notification'

Vue.use(Notifications)
```
```javascript
// nuxt.config.js
  plugins: [
    '@/plugins/auth-mixin.js',
    { src: '@/plugins/vue-notification.js', ssr: true }
  ],
```

**Expected behavior**
Working styles and proper positioning at page

**Screenshots**
There is notification. It should be placed at top right corner, and of cource have to have some styles. The orange line its just paint to show where notification is.
![image](https://user-images.githubusercontent.com/16718103/61520024-5b5be280-aa1e-11e9-9998-1d28db17c599.png)

**Desktop (please complete the following information):**
 - OS: Manjaro 18
 - Browser Chrome
 - Version 75

**Comment by andreynazarov3** [comment]
hi, i found how to fix that. you make to files in `plugins/` folder and import them separately for client and server modes
```
// nuxt.config.js

plugins: [
    { src: '~/plugins/notifications-ssr', mode: 'server' },
    { src: '~/plugins/notifications-client', mode: 'client' }
]
```
```
// notifications-ssr.js

import Notifications from 'vue-notification/dist/ssr.js';
import Vue from 'vue';

Vue.use(Notifications);
```
```
// notifications-client.js

import Notifications from 'vue-notification';
import Vue from 'vue';

Vue.use(Notifications);
```

**Comment by IngvarListard** [comment]
Thanks! It works for me!

**Comment by mikhailsidorov** [comment]
Why is this not in the documentation?
