### ISSUE TITLE
[Suggestion] Give events Vue instance a proper name

### ISSUE THREAD

**Issue by webketje** [euvl/vue-notification#141]
### Issue

vue-notification emits generically-named `add` events through a separate Vue `#root` instance. Detected through Vue Devtools, it isn't clear that this `#root` is not the main app `#root`. Moreover, if an implementor **did** define an `add` event on the root instance (eg. for a simple CRUD SPA), this would cause even more confusion.

### Solution

In `events.js`, add a `name: 'VueNotification'` property to the Vue instantiation options, then Vue DevTools will properly distinguish it from the app `#root`:

````js
export const events = new Vue({ name: 'vue-notification' });
````

Vue Devtools preview:

![image](https://user-images.githubusercontent.com/1928531/62331842-8550e280-b4bd-11e9-8e0e-edc2ca325c25.png)

**Comment by euvl** [comment]
I didn't know you can do it 😄
