### ISSUE TITLE
[Vue warn]: Invalid default value for prop "position"

### ISSUE THREAD

**Issue by DTX-92** [euvl/vue-notification#15]
[Vue warn]: Invalid default value for prop "position": Props with type Object/Array must use a factory function to return the default value.

found in
```
---> <Notifications>
```

**Comment by fakiolinho** [comment]
I think this patch is not published @euvl right?

**Comment by euvl** [comment]
Nope, will do tonight. It was closed due to annoying Github feature to close issues what start with 'Fix' keyword. Keep forgetting about it.. :-/

**Comment by euvl** [comment]
that*

**Comment by fakiolinho** [comment]
Haha, great. Thanks for your great efforts @euvl  😄

**Comment by euvl** [comment]
Thanks, published in `1.3.2`
