### ISSUE TITLE
Set css postion:absolute

### ISSUE THREAD

**Issue by YuJianghao** [euvl/vue-notification#150]
**Is your feature request related to a problem? Please describe.**
If I want to change the place of the notification from whole screen to main content area( which means notifications will not overlay navbar), the setting in a .css file will not work. I must add style inside the Vue component which always be a layout component.

**Describe the solution you'd like**
Can I have a prop that set the notification style to positon:absolute

**Describe alternatives you've considered**
Any other way to achieve the goes without have to add css inside a layout component.

**Additional context**

**Comment by nidilasi** [comment]
Try overriding the CSS to your liking.
```
.notifications {
    position: absolute;
}
```
