### ISSUE TITLE
the default instance name this.$notify conflict with the element UI's notification method this.$notify

### ISSUE THREAD

**Issue by royliu007** [euvl/vue-notification#157]
项目中全局引入element ui 的同时，发现调用 this.$notify 的时候调用的是 element ui 的notification 组件，看了半天才找到可以通过更改名称来解决这个冲突，但是readme 中并没有详解！希望对遇到的同学有帮助

Vue.use(Notifications, { name: 'myNotify', velocity })

methods: {
    getNotification() {
      this.$myNotify({
        group: 'foo',
        title: 'Important message',
        text: 'Hello user! This is a notification!'
      })
    }
  }

**Comment by euvl** [comment]
You can try to rename it in the project but i would not change plugins api.
