### ISSUE TITLE
v-if for item.text

### ISSUE THREAD

**Issue by horshechnyk** [euvl/vue-notification#159]
**Is your feature request related to a problem? Please describe.**
i need margin between title and text, so i add style
but when i use only title, i have empty div for text with margin

**Describe the solution you'd like**
v-if will fix it

**Additional context**

![image](https://user-images.githubusercontent.com/57791249/69728609-6aba0d80-112d-11ea-9267-fbe57076726f.png)
![image](https://user-images.githubusercontent.com/57791249/69729070-5c202600-112e-11ea-9618-2d4dc950e883.png)

**Comment by nemeton-x** [comment]
Hello @horshechnyk  
so you can probably achieve what you need with slot-scope([vue slot-scope docs](https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax)). 

Just add `slot-scope="slotProps"` in your slot line, and you shall have the access to parent data in `slotProps.item`.

```
<notifications width="600" group="notificationWithButtonGroup" position="bottom right">
    <template slot="body" slot-scope="slotProps">
        <div class="notification-title">
            <div v-if="slotProps.item.title">{{ slotProps.item.title }}</div>
        </div>
    </template>
</notifications>
```
