### ISSUE TITLE
CSS Animation: disappearing notification twitches when you insert second notification

### ISSUE THREAD

**Issue by DTX-92** [euvl/vue-notification#16]
I tried to set up speed to 3000ms and duration to 500ms.
As a result, appearence speed was like 3000ms, duration was 5000ms and dissappering speed was 50-2000ms.
Also disappearing notification twitches when you insert new notifications.
Here is a gif with twitches:
![gif1](http://i.imgur.com/Fj1XE5R.gif)
And here is a gif with speed set to 3000ms and durations to 500ms:
![gif2](http://i.imgur.com/ATTI147.gif)

**Comment by euvl** [comment]
Hey @DTX-92 thanks for your feedback, I will take a closer look into this (and sorry for a delay, have too much on my plate right now 😄 )

**Comment by pochern** [comment]
For me, when I click 'Save' and a notification is added to a group with a "top" position, the notifications in the group jump down and back up when a new notification is added. It doesn't seem to happen when other types of notifications get triggered by the other buttons though...

https://codesandbox.io/s/gifted-goldstine-2ig3vg?file=/src/components/HelloWorld.vue
