### ISSUE TITLE
Pause timeout on hover

### ISSUE THREAD

**Issue by sibiantony** [euvl/vue-notification#165]
Is it possible to pause the notification timeout on hover?
Perhaps with a property pause-on-hover.

**Comment by jeffdesign** [comment]
Did you get this to work?

**Comment by leo95works** [comment]
I have the same issue

**Comment by nemeton-x** [comment]
@sibiantony , @jeffdesign , @leo95works 
Just submitted a PR for this.
https://github.com/euvl/vue-notification/pull/173

cc: @euvl

**Comment by jeffdesign** [comment]
Thank you! 🙏

**Comment by gerzitom** [comment]
@vishalyadaviit Is this feature on production? Because I can not find it in production code. I would really love to use this feature.

**Comment by vishalyadaviit** [comment]
Hi @gerzitom ,
I don't think the project owner has released a new version for this package in a long time.
https://github.com/euvl/vue-notification/pull/173#issuecomment-654132609

@euvl Can you asses and publish a new release? 
A lot of people are using this package & seem to require this feature.

**Comment by camhammel** [comment]
+1, would really appreciate this being released
