### ISSUE TITLE
I can create notification with the interface, but default style is applied to the component

### ISSUE THREAD

**Issue by XiayidanAlimu** [euvl/vue-notification#167]
![Capture](https://user-images.githubusercontent.com/22473904/77248008-82665600-6c36-11ea-95c7-f08c200e65ce.JPG)

I don't know what is missing ....

in script tag I have: 
`this.$notify({
            group: 'foo-css',
            title: '<b>Important message</b>',
            text: e.data,
            type: 'warn'
          });`

in template Vue I have 
`<notifications group="foo-css"
                    position="top center"
                    classes="n-light" 
                    :width="400"/>`

**Comment by nemeton-x** [comment]
@XiayidanAlimu see this might be helpful
https://github.com/euvl/vue-notification/issues/171#issuecomment-634933154
