### ISSUE TITLE
Add a way to listen to new notifications

### ISSUE THREAD

**Issue by Yaty** [euvl/vue-notification#17]
Hi,
Thanks for vue-notification !
I would like to be able to listen for new notifications with a callback function per example. It can be useful if you want to store notifications on a backend.
What do you think ? I could try and send a PR ?

**Comment by euvl** [comment]
Hey, 

Thanks for kind words 😄 
Tbh I am not entirely sure what you mean. 

"be able to listen for new notifications" - but you already are in charge of showing notifications, which means that you have control over them, which also means tou know when new notifications have to created.

"want to store notifications on a backend" - the plugin designed just to show notifications, if you need to store them on backend and query your backend for new notifications its entirely up to the implementation of your application.

**Comment by Yaty** [comment]
Yes I do know when I create my notifications, I could just send a request to my backend every time I create a notification (that means one call to a function at each $notify() call, with a risk to forget it :D). 
The idea would be to have one listener (a callback function) that will be called every time a notification is created. 
But yes, I could implement that in my own app, I thought it would be cool to have that in Vue-notifications but that's maybe overkill :)

**Comment by euvl** [comment]
Hey, sorry for a delay 😄 

You can wrap your notify + post call into one function and extend vue prototype. Abstract example:

```javascript
Vue.prototype.extendedNotify = function (payload) {
  httpLibrary.post('/foo', payload)
    .then(() => {
      this.$notify(payload)
    })
}

```

And ofc I would not mind PRs 😄 . The better solution though might be to $emit an event when notification is destroyed (before animation starts and/or after animation finished).
