### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dschiller** [euvl/vue-notification#170]
**Describe the bug**
Notify not working

**To Reproduce**
1. `npm install --save vue-notification`
2. Add to `app.js`
```
import Notifications from 'vue-notification'

Vue.use(Notifications)
```
3. Add to Vue File
```
<template>
  <p>Hello World!</p>
</template>

<script>
    export default {
        mounted: [
            this.$notify({
                group: 'foo',
                title: 'Important message',
                text: 'Hello user! This is a notification!'
            })
        ]
    }
</script>
```
![image](https://user-images.githubusercontent.com/3144986/79058758-4b51f600-7c72-11ea-8e1b-e9549986aab3.png)

**Expected behavior**
Notification should be visible without Errors in the Console.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81

**Smartphone (please complete the following information):**
None

**Additional context**
None

**Comment by euvl** [comment]
Your `mounted` is an array, should by a function `mounted () { .. .}`
