### ISSUE TITLE
CSS classes interfere with vuetify classes 

### ISSUE THREAD

**Issue by JensVanhulst** [euvl/vue-notification#185]
**Describe the bug**
The classes of the default notifications (success, warning, error) interfere with the success, warning, error classes of vuetify.

**To Reproduce**
1. Create vue (v2.6.11) app with vuetify added as a plugin ( v2.2.11)
2. Create a basic component and add the JS code in a mounted hook

```html
<template>
   <notifications app class="mt-3 notification-group" group="notifications" position="top right" />
</template>
```
```js
mounted() {
 this.$notify({
              group: 'notifications',
              type: 'success',
              title: 'User deleted successfully',
              duration: 30000000,
              speed: 1000,
            });
}
```
**Expected behavior**
You should be able to use vue-notification simultaneous with vuetify. 

**Screenshots**
![Screenshot 2020-07-24 at 22 09 12](https://user-images.githubusercontent.com/43351822/88431881-7a444000-cdfb-11ea-8309-fc5daacfaf66.png)

In this picture you can see that the success class of the vuetify framework is applied ```v-application .success { }``` and overwrites the notify class
This causes the following behaviour :

When vuetify class disabled : 

![Screenshot 2020-07-24 at 22 14 46](https://user-images.githubusercontent.com/43351822/88431743-3e10df80-cdfb-11ea-9a45-e18d8bd2191b.png)

When vuetify class enabled :

![Screenshot 2020-07-24 at 22 14 35](https://user-images.githubusercontent.com/43351822/88431771-4a953800-cdfb-11ea-9192-52f5494c3c71.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.5
 - Browser : Chrome (v84.0.4147.89)

**Comment by hmaesta** [comment]
Related to #122.

**Comment by JensVanhulst** [comment]
@hmaesta To be clear this aren't custom classes. These are just  the default classes of the framework and the plugin. 
I tried to change the import order tho, but no success. 

I think the only way to fix is problem is to prefix the classes to something like `vn-success` so the class doesn't get overwritten by the plugin ?
