### ISSUE TITLE
Cannot set width of alert

### ISSUE THREAD

**Issue by GeRaged** [euvl/vue-notification#188]
**Describe the bug**
It is not possible to set the width of the notification

**To Reproduce**
`        this.$notify({
          duration: 3000,
          width: '100%',
          text: 'Testing the notification system!',
        });`

**Expected behavior**
The notification width should be 100%

**Screenshots**
https://prnt.sc/u6puc4

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Firefox Developer Browser

**Comment by mcahriman** [comment]
Works only when passed as a prop
