### ISSUE TITLE
How to import in component and not in main.js?

### ISSUE THREAD

**Issue by ricky11** [euvl/vue-notification#190]
Can i import this module and use it in a component rather then globally?

Components dont have access to Vue.use unless import vue again which i dont think i should do.

import Notifications from 'vue-notification'
components : {Notifications}

but then how to call this.$notify, it wont work like this. sorry this may not be a vue-notification related question.

Thanks.

**Comment by rwaddin** [comment]
same problem
have you found a solution?

**Comment by ricky11** [comment]
Well, yes but im not sure its ideal. As with any module you can always import it directly in to the component that needs it, and call Vue.use there, but then you need to also import vue in the component also.
