### ISSUE TITLE
Vue3 Support

### ISSUE THREAD

**Issue by aurium** [euvl/vue-notification#198]
**Is your feature request related to a problem? Please describe.**
`vue-notification` is not compatible to Vue3.

**Describe the solution you'd like**
I want to use `vue-notification` in a Vue3 app.

**Describe alternatives you've considered**
The alternative is to use another notification component.

**Comment by mcdis** [comment]
1. I've replace `new Vue()` like  event bus on this
```
class Event {
  constructor() {
    this.events = {};
  }

  on(eventName, fn) {
    this.events[eventName] = this.events[eventName] || [];
    this.events[eventName].push(fn);
  }

  off(eventName, fn) {
    if (this.events[eventName]) {
      for (let i = 0; i < this.events[eventName].length; i++) {
        if (this.events[eventName][i] === fn) {
          this.events[eventName].splice(i, 1);
          break;
        }
      }
    }
  }

  emit(eventName, data) {
    if (this.events[eventName]) {
      this.events[eventName].forEach(function (fn) {
        fn(data);
      });
    }
  }
}

export default new Event();
```

2. remove velocity plugin

and it works...

**Comment by lewis-munyi** [comment]
How do I use this in Vue 3? I keep getting the error 
`index.js?ee98:146 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_vue___default.a is not a constructor`

// main.js
```
import Notifications from 'vue-notification'

const app = createApp(App)
app.use(store)
	.use(router)
	.use(Notifications)
	.mount('#app')
```

// Vue component
```
this.$notify({
                group: 'auth',
                title: 'Important message',
                text: 'Hello user! This is a notification!',
            })
```

How do I fix this?

**Comment by dacoto97** [comment]
+1

**Comment by professrr** [comment]
+1

**Comment by RRicardotj** [comment]
Same here, I'm try to use it in Vue 3, but it's not working. I get the error
`index.js?ee98:146 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_vue___default.a is not a constructor`

**Comment by j-jalving** [comment]
+1

**Comment by iwannabecool** [comment]
It is look like this repo not maintained anymore. I forked this repo and rewrite in TypeScript and Vue 3, you can try it here:
https://github.com/iwannabecool/vue3-notifications

**Comment by dacoto97** [comment]
Is there any news?

**Comment by patrick-motard** [comment]
This repo should be marked as archived if this is the case.
