### ISSUE TITLE
Group won't work

### ISSUE THREAD

**Issue by ver1000000** [euvl/vue-notification#2]
Hi. Thank you for good plugin, I like it. 

As I understand grouping prevents the same notifications, but if I enable group notifications it won't work.

 ```
Vue.http.interceptors.push(function(request, next) {

    next(function(response) {

        switch (response.status) {
            case 401:
                console.error('You are unauthorized');
                this.$notify({
                    group: 'unauthorized', // notifications will work if commented
                    title: 'You are not authorized',
                    type: 'error',
                    text: 'Log out ...',
                    duration: 99999999
                });
                break;
            case 404:
                this.$notify({
                    title: 'Page not found',
                    type: 'error'
                });
                break;
            default:
                this.$notify({
                    title: 'Unknown error'
                });
        }

    });
});
```

**Comment by euvl** [comment]
Hey, it does not work exactly like that, the readme I've wrote is a bit confusing 😢 . 
The way groups work is: 

If you have 2 notification holders, like that: 

```
<notifications position="top right" name="system" />
<notifications position="top left" name="auth" />
```

You can use `group` parameter to specify which notification holder you want to use. 
```
//Will print it in the notifications holder "auth" which will be in top left corner
this.$notify({ group: 'auth', text: 'Fooooo!' }) 
```

The reason I've done that is that in my project there were 2 different types of notifications: 
1. Auth-based, eg. "you are not authorized", "license is out of data", etc 
2. System-based, eg. "File was deleted", etc 

And they required different styling.
---
Hope that helped, I am currently doing update to make it a bit less confusing, and I did not expect someone to start using it so soon 👍 🔥 😄 

Thanks :)

**Comment by ver1000000** [comment]
Thank you for explanation. Now I see. 
But what do you think about preventing the same notifications?

When my page loads it makes 3-4 requests and each returns 401 error. So I need prevent the same notifications manually(

**Comment by euvl** [comment]
I am afraid I am not planning to do it. What you've described sounds pretty custom to your app. There are number of simple ways to implement this type of functionality (for example put debounce period if your error code is 401) 👍
