### ISSUE TITLE
Todo: 100% width notification

### ISSUE THREAD

**Issue by ilgarm** [euvl/vue-notification#21]
Hi! Great plugin. One question: is there a way to create notification that occupies 100% width of the window? Thanks!

**Comment by euvl** [comment]
Hey @ilgarm, thanks! 

Currently you have to specify length with pixels, so answer is no, you cant do it I am afraid. As an option you can try settings width to 9999px or smth, but I do not know if it will work :)

**Comment by euvl** [comment]
I think I will implement it, hopefully this weekend 😄

**Comment by ilgarm** [comment]
Hi Yev, thanks for prompt response and support! :)

**Comment by euvl** [comment]
Hey @ilgarm, from version `@1.3.4` you can set width using strings with `%` and `px`, for example `100%`

👍

**Comment by ilgarm** [comment]
@euvl, fantastic, thanks a lot! I will give it a try on weekend.

**Comment by euvl** [comment]
Awesome, thanks!
