### ISSUE TITLE
width not working

### ISSUE THREAD

**Issue by asalgan** [euvl/vue-notification#213]
I am setting the width as a prop:

```
this.$notify({
   text: "This is text", 
   type: 'success', 
   width: '50px',
   duration: 1000
});
```

And it still defaults to the 300px. There is nothing in my code overriding this, it just continues to default to 300px. It also does not change if I set the width to be a percentage as well

**Comment by joeslyon** [comment]
<notifications group="foo" width='50px'/>

**Comment by joeslyon** [comment]
```js
<notifications group="foo" width='50px'/>
```
