### ISSUE TITLE
Option to call Notify in Vuex? 

### ISSUE THREAD

**Issue by devzom** [euvl/vue-notification#217]
**Is your feature request related to a problem? Please describe.**
Is there an option to use it within Vuex with globally configured styles and to pass dynamic 'title' to it?

 :)

**Comment by davestewart** [comment]
See the docs:

Or trigger notifications from other files, for example, your router:

```js
import Vue from 'vue'

Vue.notify({
  title: 'Authorization',
  text: 'You have been logged in!'
})
```

**Comment by devzom** [comment]
Alright! Thank You for the answer! :)
