### ISSUE TITLE
Any chance you can publish the latest version?

### ISSUE THREAD

**Issue by davestewart** [euvl/vue-notification#218]
NPM is showing not published for 2 years...

https://www.npmjs.com/package/vue-notifications

**Comment by lucas-santosP** [comment]
I was hoping for this too. I like the pattern and syntax of this lib, would like to use the timer pause on hover feature that was added a couple of months ago. But it seems that the library is no longer maintained.

**Comment by davestewart** [comment]
It is, as my [PR](https://github.com/euvl/vue-notification/pull/211) was merged last month; _just not published_.

@euvl ?

**Comment by kyvg** [comment]
https://github.com/euvl/vue-notification/issues/198#issuecomment-820348076

**Comment by gmirmand** [comment]
For information, I publish a fork.
[#293](https://github.com/euvl/vue-notification/issues/293)
