### ISSUE TITLE
Add ability to set default parameters

### ISSUE THREAD

**Issue by soichih** [euvl/vue-notification#22]
I want to display all notifications on the bottom right corner, but I don't want to configure it every time I invoke notification. Is there a way to set (override) the default configuration options in a single location?

For example, I'd like to be able to do 

```
import Vue           from 'vue'
import Notifications from 'vue-notification'

Vue.use(Notifications, {position: "bottom right"})
```

Thank you!

**Comment by euvl** [comment]
You dont have to configure it every time. You have to create your 

<notifications position=top right" />

Only once, lets say in your <App/> root, and you can invoke $notify from anywhere.

**Comment by soichih** [comment]
Ah.. I've missed that from README. Thanks!

**Comment by tcjdesign** [comment]
Glad this issue existed, I would have also missed it from the docs.

I think we can make this clearer. Even a line or two saying that you can set defaults for any of the possible props inside the `<notification>` elem would help. While obvious on the other side, that of course we can set the props in the element to which the props apply, it's less than obvious to less-experienced devs.

**Comment by euvl** [comment]
@tcjdesign I will be happy to review your changes to the documentation, other than that i am afraid i dont have enough time right now to rewrite docs :(
