### ISSUE TITLE
Unable to add custom css class

### ISSUE THREAD

**Issue by UgurBasural** [euvl/vue-notification#224]
```
<notifications
      position="top center"
      width="30%"
      :duration="-10000"
      :max="2"
      classes="notification"
    />
```

```
<style scoped lang="scss">
.notification {
  padding: 10px;
  margin: 0 5px 5px;

  font-size: 12px;

  color: #ffffff;
  background: #44a4fc;
  border-left: 5px solid #187fe7;

  &.warn {
    background: #ffb648;
    border-left-color: #f48a06;
  }

  &.error {
    background: #e54d42;
    border-left-color: #b82e24;
  }

  &.success {
    background: #187fe7;
    border-left-color: #187fe7;
  }
}
</style>
```

My code is like in the above and output is like this : 
<img width="1364" alt="Screenshot 2021-04-01 at 14 09 50" src="https://user-images.githubusercontent.com/26435106/113285754-fdefee00-92f3-11eb-93c7-e246a94daada.png">

**Comment by patrick-motard** [comment]
I'm also having this issue. This shouldn't be closed due to inactivity. It's still an issue.

**Comment by foofel** [comment]
same for me, `vue-notification-template` seems to overwrite the background from my own class but i dont understand yet why. only happens in release mode for me.
