### ISSUE TITLE
Implement TypeScript

### ISSUE THREAD

**Issue by yarkovaleksei** [euvl/vue-notification#227]
**Is your feature request related to a problem? Please describe.**
Planning to rewrite in TypeScript?

**Describe the solution you'd like**
I would like to suggest rewriting in TypeScript to facilitate future support.

**Comment by iwannabecool** [comment]
I forked this repo and rewrite in TypeScript and Vue 3, you can try it here:
https://github.com/iwannabecool/vue3-notifications
