### ISSUE TITLE
Add some test coverage

### ISSUE THREAD

**Issue by crcatala** [euvl/vue-notification#23]
@euvl thanks for creating this fantastic lib! compared with other toast/notification vue libs, and this definitely was the nicest API and great customization (especially slots and even swapping out animation libs).

Would be great to add some test coverage. Might help others contribute to this lib and guard against breaking behavior.

Will push up an example PR shortly

**Comment by euvl** [comment]
Awesome, tests is clearly must have. I will review the pr tomorrow! 👍👍👍👍👍

**Comment by euvl** [comment]
Great job, merged into master!
