### ISSUE TITLE
closeOnClick: false doesn't work when using the API

### ISSUE THREAD

**Issue by emiliemarchand** [euvl/vue-notification#245]
**Describe the bug**
Setting the option "closeOnClick: false" doesn't work when triggering a notification via the API.

**To Reproduce**

1. In a Vue component, trigger a notification like this:
```
this.$notify({
    type: 'warn',
    text: "This is a test",
    duration: -1,    
    closeOnClick: false
});
```
2. Click on the notification that pops up
3. The notification closes

**Expected behavior**
The notification should not close.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 93

**Additional context**
The only way I could make it work is by setting the option as a prop on the html tag, which is quite inconvenient because I do not want all notifications to behave this way.
```<notifications :close-on-click="false" position="top center" width="100%"></notifications>```

**Comment by emiliemarchand** [comment]
Why is this closed? It's not fixed.

**Comment by ricky11** [comment]
having the same issue, the doc says `closeOnClick`  but you used : close-on-click

i tried both still does not work.

**Comment by Mat3uszkek** [comment]
If you need to include a button within the notification for executing further actions, but find that the notification closes upon clicking the button despite setting close-on-click: false, applying event.stopPropagation() within the button's event handler function can prevent this behavior.
