### ISSUE TITLE
Add hide method to close notifications 

### ISSUE THREAD

**Issue by OasisLiveForever** [euvl/vue-notification#27]
Hi,

it would be great to hide programmatically all notifications of a group trough a hide method.
What do you think?

**Comment by euvl** [comment]
Hi @OasisLiveForever, 

Sounds reasonable, what's your use-case?

**Comment by OasisLiveForever** [comment]
Hi,

sometimes I want to hide all notifications before navigating to a component.

Sometimes I want to have only one notification per group so I would like to clear all notifications of the group before showing a new notification (for this purpose it could be useful to have a max number of notification per group).

**Comment by euvl** [comment]
Okay, hiding everything before doing navigation sounds pretty good, also your point about `o have a max number of notification per group` made me think that `:max="10"` prop would be also something useful.

Thanks, I will create corresponding issues for these 2 features and will try to spend some time on them next week 👍  👍

**Comment by euvl** [comment]
Hey @OasisLiveForever, i've added both features that we discussed in version `1.3.3` 👍
