### ISSUE TITLE
vue 3 support

### ISSUE THREAD

**Issue by robertsulkowskiclicktrans** [euvl/vue-notification#280]
Hi,
thank you for your excellent package. However we're approaching the point when we have to move to vue 3, since vue 2 will be deprecated until the end of the year. Is there any chance you'd release a version which supports vue 3?

Best,
Robert

**Comment by andrey-fanin** [comment]
If you still need it, here is a fork of this lib for Vue 3.
https://github.com/kyvg/vue3-notification

> Hi, thank you for your excellent package. However we're approaching the point when we have to move to vue 3, since vue 2 will be deprecated until the end of the year. Is there any chance you'd release a version which supports vue 3?
> 
> Best, Robert

**Comment by robertsulkowskiclicktrans** [comment]
Thank you!
