### ISSUE TITLE
peer of vue 2 causes issue when compiling in vue 3

### ISSUE THREAD

**Issue by KnowledgeGarden** [euvl/vue-notification#284]
**Describe the bug**
Could not resolve dependency:
npm ERR! peer vue@"^2.0.0" from vue-notification@1.3.20

**To Reproduce**
Building https://github.com/gazi-dis/vue3-todo-withapi
Compiled one time. Then added cors to package.json and that issue rose.
Removed cors,  deletec node-modules and compiled again. Cannot get it to compile.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Could a new version be created where the peer is vue 3?

**Comment by Eloy-Gonzalez** [comment]
try with this package

https://github.com/kyvg/vue3-notification
