### ISSUE TITLE
How to use outside a component

### ISSUE THREAD

**Issue by OgaBoss** [euvl/vue-notification#36]
Hello @euvl, great job on this plugin, but i would like to know, how i can use this plugin outside of a vue component, like let say i have an api.js file where am making all my api calls, and i want to make use of the plugin in there.
Thank you.

**Comment by euvl** [comment]
Hey @OgaBoss, Thanks. 

This plugin requires instance of Vue to work. You can try doing `var instance = new Vue()` in your api calls file or you could pass Vue instance from your root component, for example:

```
mounted () {
  api.setVueInstace(this)
}
```
api:
```javascript
let vue = null

export default {
...
setVueInstance (instance) { vue = instance }
}
