### ISSUE TITLE
Notifications from child components

### ISSUE THREAD

**Issue by SwanMougnoz** [euvl/vue-notification#37]
I'm confused about how to use this plugin. The $notifiy method rely on $emit to add new notifications to the <notifications> component. If I got it right, referring to the vue documentation [here](https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events), I cannot put my notifications component at a top level in the component tree or it will not receive any event. 

Where should I put this component ? At the same level that my "emitting" components ? This means that I have to declare it multiple times for each place I want to use it ? I must be missing something.

**Comment by euvl** [comment]
Hi @SwanMougnoz,

It uses a global event bus that allows you to trigger events from anywhere in your component tree and $notify is just a wrapper for this fn.

**Comment by SwanMougnoz** [comment]
Thank for your reply. By the way it does not work for me. Notifications only show up when triggered from a parent or same level components. This is probably not an actual issue, I will figure out what is missing I guess. Thank again.

**Comment by taobad** [comment]
> Thank for your reply. By the way it does not work for me. Notifications only show up when triggered from a parent or same level components. This is probably not an actual issue, I will figure out what is missing I guess. Thank again.

Did you figure out what happened eventually? i'm having similar issue
