### ISSUE TITLE
Position doesn't seem to work

### ISSUE THREAD

**Issue by TerryMooreII** [euvl/vue-notification#38]
Even with `bottom right` in the notification object it still shows up in the top right. 
```
      this.$notify({
        group: 'messages',
        position: 'bottom right',
        title: 'Important message',
        type: 'error',
        text: 'Hello user! This is a notification!'
      });
```
Is there something that I have incorrect?

Using version 1.3.4

**Comment by euvl** [comment]
Hi. You should set position on Notifications component. Please look into readme.

**Comment by TerryMooreII** [comment]
Ah, Yes that worked, i took props as properties of the $notify object.  

For others that search for this here is what fixed it
```
<notifications group="messages" position="top center"/>
```

**Comment by yogesh-xseed** [comment]
it could be helpful if we could control from the $notify object.

**Comment by euvl** [comment]
For the suggestion above - one would need to mount containers for each position every time (ie system will not know upfront where you will want to show your notification - hence should be "ready")... which is 6 components.

This means that it will just eat memory and pollute the component tree for most of the users who will never use this feature.
