### ISSUE TITLE
Vuex Integration

### ISSUE THREAD

**Issue by Esslamb** [euvl/vue-notification#39]
Just looking for some help/advice on how to integrate with Vuex. Currently, my implementation is:

import Notifications from 'vue-notification'
Vue.use(Notifications)

And this works fine in Vue but when I try to access the $notify from Vuex it doesn't seem to be attached to the Vue instance. I might try to create a Vue component that watches on a store model which just triggers the notification from within in the component. I appreciate this isn't an issue but I'm sure a lot of people will find it helpful. Thanks in advance.

**Comment by euvl** [comment]
Hey @Esslamb, thanks for using plugin!

Ideally you would not use $notify in vuex - it means you are mixing your model (data layer) with view (representation layer).

If I were doing this, I probably would wrap `$commit` and `$notify` into mixin:

```
  {
    methods: {
      commitAndNotify (title, text) {
        this.$commit('ADD_NOTIFICATION', { title, text })
        this.$notify({ ... })
      }
    }
  } 
```

**Comment by euvl** [comment]
Or if you are using actions you can return promise and do:

```
this.$dispatch('woot').then(() => { this.notify(..) })
```

**Comment by Esslamb** [comment]
Thanks for the quick reply! I actually went off and tried to come up with a solution based on your suggestions. I never heard about mixins so I did a little digging but I realised they wouldn't be able to solve my problem because some of my actions/mutations are dispatched via other stores. My other concern was as you mentioned I didn't want to mix my model later with my views but some of my API request where going out via Vuex so they would never hit a view. Based on the above information I came up with the idea of creating a notification store that would hold the current notification properties and a toggle property thus separating the concerns.

```javascript
export default {
    namespaced: true,
    state: {
        show: false,
        title: '',
        text: '',
        type: '' 
    },
    mutations: {
        showNotify(state, { title, text, type }) {
            state.show = true
            state.title = title
            state.text = text
            state.type = type
        },
        disableNotify(state) {
            state.show = false
        }
    }
}
```
Next, I went to my main app.vue file and attached the mutations and state. I had to add an extra disable notify mutations which would toggle the store so I wouldn't get problems when the calling the commit from multiple different locations.

```javascript

computed: {
        ...mapState({
                show: state => state.notify.show
            }),
        },
        watch: {
            show() {
                if (this.show) {
                    this.$notify({
                        title: this.$store.state.notify.title,
                        text: this.$store.state.notify.text,
                        type: this.$store.state.notify.type,
                        group: 'notification'
                    })
                }
                this.disableNotify()
            }
        },
        methods: {
            ...mapMutations('notify', [
                'disableNotify'
            ])
        },
```

And finally, I just commit showNotify whenever I need a notification.

```javascript
 context.commit('notify/showNotify', {
  title: 'Notificaton',
  text: 'Something went wrong! Failed to fetch the list of users',
  type: 'error'
   }, { root: true })
```

Sorry about the long winded reply but I thought it might benefit others if they got stuck! Keep in mind this works because my App.vue file encases all my other components which should be fine because the basis of the plugin relies on you adding the component to a global parent.

Thanks for the help @euvl

**Comment by euvl** [comment]
Nice one, i've tried to simplify a bit your example:

```js
// notification.js
export default {
  namespaced: true,  
  state: {
    queue: [],
    max: 5
  },
  mutations: {
    // Push to queue and make sure that the size does not exceed "max" count
   // (we don't like memory leaks, do we? :)
    push (state, notification) {
      state.queue.push(notification)

      if (state.queue.length > state.max) {
        state.queue.shift()
      }
    }
  }
}

//app.js
{
  computed: {
    ...mapState({
      queue: state => state.notify.queue
    }),
  },
  watch: {
    queue: {
      handler: function (queue) {
        let queueTop = queue[queue.length - 1]

        this.$notify({ ...queueTop, group: 'notification' })
      },
      immediate: true,
      deep: true
    }
  }
}
```

i don't think that it works straight away as i can't test it now, but the idea is to keep a limited length  queue of elements. This way you will be sure that multiple notifications will not "replace one another" and also "hiding" notification will be handled by plugin.

**Comment by Esslamb** [comment]
That's awesome dude it worked like magic! I still have a lot to learn 👍 . I appreciate you taking out the time to improve it.

I'm happy to close this issue but it seems like wasted knowledge. If you want I can pull request an addition to the docs with 'Example Vuex Implementation' to give others a little help?

**Comment by euvl** [comment]
No problem 😄 
Worry not, I've got `FAQ` label for issues 😄

**Comment by Shuliyey** [comment]
Here's a hacky way to do it, in the `store.js`

```
      Vue.prototype.$notify({
        group: 'success2',
        title: '测试通知!',
        text: 'Это текст уведомления!',
        type: 'success'
      })
```

**Comment by victorelu** [comment]
@Shuliyey I know this issue has already been closed, but I'm curious if you calling this solution _hacky_ means there are downsides to using it - and if so, what are they?

**Comment by Shuliyey** [comment]
@victorelu technically there's no downside. But i think it's more appropriate to call `$notify` method like this

```js
      this.$notify({
        group: 'success2',
        title: '测试通知!',
        text: 'Это текст уведомления!',
        type: 'success'
      })
```

e.g the vue-resource plugin https://github.com/pagekit/vue-resource, when this plugin is used/imported to the Vue app

you can call its `http` method like this (the `http` method is binding to `Vue` object itself)

![image](https://user-images.githubusercontent.com/4773348/37271897-f5b2d60c-2628-11e8-8f4d-d1d3a3eef4e5.png)

Follow this convention i think the `notify` method should be able to be used like this
```js
Vue.notify(
```

But yeah this is just my personally view to keep code more consistent

**Comment by euvl** [comment]
Vue resource does put any DOM nodes in the tree and thats why you can use it as `Vue.blhblah`.

**Comment by Kaffiend** [comment]
@euvl Thank you for the `FAQ` labels, this saved me a lot of time. 👍

**Comment by alckor127** [comment]
Thanks you!!
