### ISSUE TITLE
Add clickable text (like 'Undo')

### ISSUE THREAD

**Issue by nickhough** [euvl/vue-notification#40]
Is there a way to capture click events on text within the notification and prevent it from closing? I've tried a few things, but haven't had any success. My goal would be to have a notification that says something like "John Doe has been archived. Undo".

**Comment by euvl** [comment]
Hey @nickhough

One option is to try to create a custom template: https://github.com/euvl/vue-notification#custom-template-slot

Where you will have something like this: 
```
...
{{props.item.text}} <span @click="domystuff">Undo</span>
...
```

Other option might be to append html to your message:

```
<span onclick="globalFunctionUndo">Undo<span>

window.globalFunctionUndo = () => {}
```

p.s. those are just the ones i came up with straight away, mb there are more convenient ways to do it.

**Comment by nickhough** [comment]
I couldn't seem to figure out how to pass a notification specific click handler to the custom template.

I tried

`
this.$notify({
        title: 'Restored',
        type: 'success',
        text: `${person.first_name} ${person.last_name} was restored.`,
        domystuff: this.test,
 });
`
with
`
...
{{props.item.text}} <span @click="domystuff">Undo</span>
...
`

**Comment by euvl** [comment]
you can do 
```
...
this.$notify({
        title: 'Restored',
        type: 'success',
        text: `${person.first_name} ${person.last_name} was restored.`,
       data: { callback: this.test },
 });
...
```

```
...
{{props.item.text}} <span @click="props.item.data.callback">Undo</span>
...
```

Something like that.
