### ISSUE TITLE
Plugin outputs vue development tip to console

### ISSUE THREAD

**Issue by Ortix92** [euvl/vue-notification#43]
So it took me some time to hunt this down but it turns out that this plugin forces the vue development tip and devtool tip to be displayed in the console regardless of environment (production or dev).

```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
/home/skully/Code/ethercat-gui/node_modules/vue/dist/vue.runtime.common.js:7751 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

I tried disabling it by force in `Vue.config` but that didn't help at all. 

I then commented all the references of the plugin throughout my code but left the `import` intact. Toggling the input also toggles the development tip.

I tried this in a clean `electron-vue` project (https://github.com/SimulatedGREG/electron-vue) with the same results.

A simple `import` of the plugin causes this tip to appear. I will look through your code to see if I can find where this is coming from

**Comment by euvl** [comment]
Weird, http://vue-notification.yev.io/ clearly does not have it.

![screen shot 2017-11-11 at 22 01 11](https://user-images.githubusercontent.com/1577802/32693942-dbade582-c72b-11e7-91c6-037db72c9ad3.png)

**Comment by Ortix92** [comment]
Yeah it also baffles me because that was one of the first things I checked. I checked my webpack config too and on runtime I see that my application is in production mode so I'm really confused. Have you tried running the plugin in an electron application like I suggested above? I looked through the source and there is nothing which can cause this issue... Very weird

**Comment by euvl** [comment]
Nope, I didn't really try to run it in electron, however, I checked my work project and it does not output the message. Have no idea whats going on :)
