### ISSUE TITLE
How to get config using Laravel Mix

### ISSUE THREAD

**Issue by cholojuanito** [euvl/vue-notification#44]
Question/Help:
So I am using Laravel to make my personal website.  I have a form to send me a message on there and I want to use your notifications to display whether or not the email was sent after making an ajax request.
Specifically, I am using Laravel Mix to take care of the Webpack stuff.  (So maybe that is causing the issue).
Either way, I have attached some snippets from my code so you can have a look and see if you can help me.  The set up seemed basic enough on the readme.md but I can't seem to get the notification to show up in the Vue dev tool for Chrome.  I am fairly new to Vue so any help you can give would be much appreciated.  Your notification components are the best I've found that are readily available.

Here is the basic file system set up for the stuff I have given you. So you understand how things are tied together.
[ js ]
    |__ [ components ]
    |            |__Modal.vue (The modal component is used in the Hero component)
    |            |__ Hero.vue
    |__ bootstrap.js
    |__ app.js (The root Vue instance is here)

Thanks again!

app.js
![app](https://user-images.githubusercontent.com/25016799/32813945-01daee5e-c96a-11e7-9f6b-b651f90cf411.PNG)
bootstrap.js
![bootstrap](https://user-images.githubusercontent.com/25016799/32813946-01f112e2-c96a-11e7-8e3a-defe8f942e2e.PNG)
modal template with notification template
![modal_part1](https://user-images.githubusercontent.com/25016799/32813947-0205ae46-c96a-11e7-9baf-dad7ac9ac242.PNG)
modal script
![modal_part2](https://user-images.githubusercontent.com/25016799/32813948-0220dd06-c96a-11e7-8608-f76f5a707680.PNG)

**Comment by euvl** [comment]
I am not using php, so I can't help you 😢 . Maybe try stackoverflow.

**Comment by cholojuanito** [comment]
Okay thank you.  I did figure it out so no worries.  Just started from square 1 declaring the notification and everything.  It's awesome! Thanks!

**Comment by euvl** [comment]
No probs :)

**Comment by MartinsZieds** [comment]
> Okay thank you. I did figure it out so no worries. Just started from square 1 declaring the notification and everything. It's awesome! Thanks!

can you explain a bit more closer?
