### ISSUE TITLE
Deprecated: scope, use slot-scope

### ISSUE THREAD

**Issue by Livijn** [euvl/vue-notification#47]
You should update the README. Replace `scope` with `slot-scope` in the custom template example. 

Error using the old: 
`(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.`

**Comment by euvl** [comment]
I don't think its anything to do with the plugin. You have to use `slot-scope` when you create your template for notification (in your code). 

If you just copied the code from docs, you will have to change scope => slot-scope because docs are written for vue 2.0 +.....
