### ISSUE TITLE
this.$notify is not defined

### ISSUE THREAD

**Issue by LRY1994** [euvl/vue-notification#50]
when I use it as your README told,it shows that this.$notify is not defined
npm install --save vue-notification

import Vue           from 'vue'
import Notifications from 'vue-notification'

Vue.use(Notifications)

this.$notify({
  group: 'foo',
  title: 'Important message',
  text: 'Hello user! This is a notification!'
});

**Comment by LRY1994** [comment]
It seems that it only can be used in a component,not any files

**Comment by euvl** [comment]
Hey, surely it should be used in component 😄  You need a vue scope to call anything at all

**Comment by vschoener** [comment]
I got the same error, I used it in the App.vue (component) and it doesn't work.

Any idea?

App.vue:
```
<script>
  import auth from './utils/auth';

  export default {
    name: 'App',
    created: () => {
      auth.fetchUser().catch((error) => {
        if (error.response.status === 403) {
          this.$notify({
            group: 'auth',
            title: 'Login failed',
            text: 'Please try again or contact us',
          });
        }
      });
    },
  };
</script>
```

main.js
```
import Vue from 'vue';
import axios from 'axios';
import VueAxios from 'vue-axios';
import Notifications from 'vue-notification';

// Style
import './assets/scss/main.scss';

// App
import App from './App';
import router from './router';

// TODO: Dynamism this value using env
axios.defaults.baseURL = 'http://api.sweetstream.com';
axios.defaults.withCredentials = true;
axios.defaults.crossDomain = true;

Vue.use(VueAxios, axios);
Vue.use(Notifications);

Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  render: h => h(App),
});
```

**Comment by tghelere** [comment]
@vschoener Any solution?

**Comment by StuartMacKay** [comment]
Add the Notifications in a components section:
```
/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  components: {
      Notifications
  },
  render: h => h(App),
});
```

**Comment by tobyhourst** [comment]
Sorry to re-open this but I have the exact same issue.

I am trying to trigger it this way in the template of a App.vue :
```
<mdb-btn href="#!" @click.native="this.$notify({
         group: 'main',
         title: 'Important message',
         text: 'Hello user! This is a notification!'
    });">
   Click
</mdb-btn>
```

I get the following error: `Uncaught TypeError: Cannot read property '$notify' of null`

I followed the documentation and my app.js file looks like this (removed unrelated stuff):

```
// require vue
window.Vue = require('vue');

import Notifications from 'vue-notification';

Vue.use(Notifications);

const app = new Vue({
	el: '#app',
	store,
	router,
	components: {
           Notifications
  	}
});
```

I get no other errors.

I use these versions:

"vue": "^2.5.17"
"vuex": "^3.1.0"
"vue-notification": "^1.3.14"

Thank you in advance for your help, I really don't know what to do here...

**Comment by tobyhourst** [comment]
Never mind, I just had to put the code in a method. It works like a charm now. Sorry.

**Comment by euvl** [comment]
@vschoener 

You have 
```
 created: () => {
```
where you loose a context of vue.js component, ot shoud be 
```
created () {
```
or 
```
created: functiion () {
```
