### ISSUE TITLE
 how to use callback in  this.$notify

### ISSUE THREAD

**Issue by danielprogramic** [euvl/vue-notification#51]
Hi, 
I would like to know how I use callback after close

 this.$notify(MessagensNotificar.success("came in"),function(){
  //***** insert another block
......................
});

**Comment by euvl** [comment]
There are not callbacks in $notify

https://github.com/euvl/vue-notification/blob/0fef530c4554c83256943b0e8d6ae680160dd368/src/index.js#L15-L23
