### ISSUE TITLE
Width is set in inline style

### ISSUE THREAD

**Issue by OasisLiveForever** [euvl/vue-notification#52]
Hi,

since width is set in inline style, I cannot change it in my custom css class.
I think width should not be passed to options but it should be set in css so we can customize it in custom css class.

**Comment by euvl** [comment]
Hi, 

thanks for recommendation, but width will stay an argument for multiple reasons. One of them is some velocity animations (in projects that are already in production) rely on having width.

**Comment by mariusa** [comment]
How can we have a different width on mobile? Or at least, have the widget set it's width to min(requested_width, viewport)
