### ISSUE TITLE
Error: Cannot read property 'offsetHeight' of null

### ISSUE THREAD

**Issue by grishkovelli** [euvl/vue-notification#57]
Hello everyone. I started to use **vue-notification**, everything is ok, but when I opened browser's console, I saw this message `Cannot read property 'offsetHeight' of null` . It happens after notification's disappearance.
I use **vue-notification** without any options, do you have any idea?

![2018-02-11_12-03-43](https://user-images.githubusercontent.com/5354813/36071783-3d97c902-0f25-11e8-9879-ca5535203d94.png)

![2018-02-11_12-20-24](https://user-images.githubusercontent.com/5354813/36071828-f705cd30-0f25-11e8-861e-1432da9ead0a.png)

**Comment by euvl** [comment]
Hey. 

This error occurs somewhere in vue framework/webpack stuff and has nothing to do with the plugin.
