### ISSUE TITLE
Incorrect positioning of icon element

### ISSUE THREAD

**Issue by mikerockett** [euvl/vue-notification#64]
![image](https://user-images.githubusercontent.com/4586280/37040649-053388b2-2163-11e8-8e55-611db165ca36.png)

Not sure if this is just me (maybe something to do with my chrome flags?)...

**Comment by euvl** [comment]
its not plugin's issue, i guess the date label is too long and flex-box handled it incorrectly

**Comment by mikerockett** [comment]
Ah, that would make sense indeed. Didn’t think about that.
