### ISSUE TITLE
220kb bundle for notifications?

### ISSUE THREAD

**Issue by cristijora** [euvl/vue-notification#7]
Great component first of all. The animations are catchy and I'm pretty curious about some implementation details but 220kb for notifications seems too much. 

Importing Vue only for sending 2 events is not a good reason to add 80kb to the bundle.
https://github.com/euvl/vue-notification/blob/master/src/index.js#L19

You can do this with a simple encapsulated store
Example here https://github.com/cristijora/vue-paper-dashboard/blob/master/src/components/UIComponents/NotificationPlugin/index.js#L9
And if you want reactivity for the list of notifications you could 
```
Vue.mixin({data:{notificationStore: NotificationStore.state}})
 Object.defineProperty(Vue.prototype, '$notifications', {
      get () {
        return this.$root.notificationStore
      }
    })
```
This way `events` which uses the empty Vue instance can be removed easily.
Also I'm pretty sure animations can be done with pure css or maybe you can partially import `velocity-animate` 

Keep up the good work !

**Comment by euvl** [comment]
Cool, thanks

**Comment by euvl** [comment]
```
Importing Vue only for sending 2 events is not a good reason to add 80kb to the bundle.
https://github.com/euvl/vue-notification/blob/master/src/index.js#L19
```
Vue is a peer dependency, e.g. it is shallow and not a part of a bundle, not quite sure what are you on about. 

```
Also I'm pretty sure animations can be done with pure css or maybe you can partially import velocity-animate
```
Great, I will be happy to review your PR if thats the case.

```
but 220kb for notifications seems too much.
```
Component itself is something like 30kb not minified. Other is `velocity` - I should prob. add it as a peer dependendency but I have no idea how it can work out.

**Comment by cristijora** [comment]
> Vue is a peer dependency, e.g. it is shallow and not a part of a bundle, not quite sure what are you on about.

Well having it as a peer dependency is ok for npm usage but not for direct script tag in html pages

**Comment by euvl** [comment]
Why?

**Comment by euvl** [comment]
If you will look in dist/index.js , first 10 lines is self invoking func that tries to bundle vue if it is in any umd global. Not 80kb.

But you are right about velocity. It takes a lot of space. I just didn't manage to make good enough animation using css (e.g. animating height from 0 to content height).

**Comment by cristijora** [comment]
Can you help me with a jsfiddle. We can give it a test if you want. Can't make a jsfiddle since the build file doesn't seem to expose the plugin in window or I'm missing something

**Comment by euvl** [comment]
Sure, awesome. Btw thanks for helping me to sort out these things. 😄 
I dont think it should be in window because it is a [umd build](github.com/umdjs/umd). 
I will make js fiddle after work (tonight/tommorow morning).

**Comment by cristijora** [comment]
Strange. Usually such a webpack config should expose in window if the
script is loaded directly. I have used simillar setups which have the same
code at the beginning of the bundle. Maybe it's because of naming
"vue-notification" in the library name. I will play a bit with it and see

**Comment by euvl** [comment]
Coolio, thanks. I am afraid my knowledge of webpack is...how to put it.. VERY limited 😄 😭

**Comment by euvl** [comment]
Hey @cristijora , wanted to let you know that i've made velocity optional, now the bundle size is 27 kb when not minified. 🥇 

Hope that if the size was a blocker now you will be able to use it. 
Thanks a lot for your feedback and motivating me to do something about it 👍 😄

**Comment by cristijora** [comment]
@euvl Great work! In the meanwhile, I made a notification component too 
https://github.com/cristijora/vue-notifyjs

Not as cool and stylish as yours though 😄 so keep up the good work !

**Comment by euvl** [comment]
Looks great, and just 3kb, nice! 👍
