### ISSUE TITLE
Override speed of velocity animations

### ISSUE THREAD

**Issue by bformet** [euvl/vue-notification#70]
Thanks for the great work.

You cannot override animation speed with $notify when using velocity.

e.g. This won't work `this.$notify({text: 'foo', speed: 0})` on velocity notifications.

**Comment by euvl** [comment]
speed should be in props (see docs)

**Comment by euvl** [comment]
check seems to be there
 https://github.com/euvl/vue-notification/blob/master/src/Notifications.vue#L212

**Comment by bformet** [comment]
Velocity animations are not based on item.speed but on props.
https://github.com/euvl/vue-notification/blob/master/src/Notifications.vue#L301


Le mer. 21 mars 2018 à 14:02, Yev Vlasenko <notifications@github.com> a
écrit :

**Comment by euvl** [comment]
yeah, should do the same check there too. Nice catch 👍
