### ISSUE TITLE
Classes Prop

### ISSUE THREAD

**Issue by nr12157** [euvl/vue-notification#73]
What's the point of the `classes` prop? If you want to have two different styles of notifications, for instance `error` and `success`, is it necessary to have two different components? So you'd need `<notifications group="success-group" classes="vue-notification success" position="bottom left" />` and `<notifications group="error-group" classes="vue-notification error" position="bottom left" />`?

I did try having one group and adjusting the `classes` prop on each call of `$notify` to change the styling, but it didn't seem to work?

        this.$notify({
          group: 'notification-group',
          title: 'Success!',
          text: 'Call time added',
          classes: 'vue-notification success'
        });

Or am I misusing the prop?

**Comment by euvl** [comment]
Hey @nr12157, yes you are misusing a prop. If you want to apply class to specific notification, use "type" parameter (https://github.com/euvl/vue-notification#api)

"classes" prop is there to apply class per notification group (a use case might be when you have message notifications and some system notifications which will prob. look completely differently).

**Comment by nr12157** [comment]
Ah that makes sense. My mistake! Thanks.

**Comment by euvl** [comment]
No problem, thanks for using plugin 👍

**Comment by ricky11** [comment]
Do you have to use scss for applying custom classes?

i added classes="my-classes" and in the css i added

.my-class and it does not apply any classes,

i also added .notification.my-class which also does not work (this is the example in the demo, but differs from the documentation, hence the confusion.. neither successfully applies the class for me.
