### ISSUE TITLE
Module build failed: Error: Couldn't find preset "latest" relative to directory 

### ISSUE THREAD

**Issue by BorjaRafols** [euvl/vue-notification#75]
Just installed the plugin and added it to my app.js file. I'm doing SSR.

```
import Notifications from 'vue-notification/dist/ssr.js'
Vue.use(Notifications)
```

Now I'm getting this error:

> Module build failed: Error: Couldn't find preset "latest" relative to directory "/src/app/node_modules/vue-notification"

I guess this is easily solvable using:
`npm install --save-dev babel-preset-latest`

However this preset is [deprecated](https://babeljs.io/docs/plugins/preset-latest/), so we should avoid it in this plugin and use babel-preset-env instead.

**Comment by euvl** [comment]
I dont think it's plugin's issue. It is already "babeled" and transpiled .
