### ISSUE TITLE
The new version 1.3.10 not load css in SSR (Nuxt)

### ISSUE THREAD

**Issue by nghiepit** [euvl/vue-notification#78]
Hi guys,

I just upgraded to 1.3.10 and have a problem in SSR.

CSS cannot load.

Thanks in advance.

**Comment by jcardell** [comment]
I can confirm this is still happening

**Comment by Blackfaded** [comment]
Having a similar problem.
When i start my dev server the toast is working correctly. But when hot module replacement begins (when I change code) the css gets broken and the notification shows as a grey block.
![Showcase](https://user-images.githubusercontent.com/19570581/50497196-e307e280-0a35-11e9-85e7-25afb0d63413.png)

**Comment by ilrock** [comment]
@Blackfaded have you managed to get it to work? I'm running the version 1.3.16 and using nuxt I still can't get the css to work

**Comment by ilrock** [comment]
In case anyone is facing this problem, as a temporary solution you can copy the css from node_modules/vue-notification/src/Notificiations.vue to your main.css file. It ain't pretty, but it works
