### ISSUE TITLE
How to use into nuxt js plugins?

### ISSUE THREAD

**Issue by GrimJacky** [euvl/vue-notification#83]
I'm using plugin inside nuxt.js project as plugin.
Use this instruction https://nuxtjs.org/guide/plugins#vue-plugins .
Then I create custom plugin which injects to app context.
```
export default ({ app }, inject) => {
  const displayAlert = (meta) => {
   this.$notify({
          group: 'alerts',
          title: 'Important message',
          text: 'Hello user! This is a notification!'
        });
    // also I'm check app.$notify
  };
  inject('displayAlert', displayAlert);
}
```
But I'm getting `undefined` error

What could be the problem?

**Comment by toadkicker** [comment]
Depending on the scope (ssr, etc) you can swap `this.$notify => app.$notify`

**Comment by toadkicker** [comment]
I don't think you can get to it this way. You can know for sure by doing `console.log(arguments)` at the top and seeing what the function has available to it.

**Comment by euvl** [comment]
```
import Notifications from 'vue-notification/dist/ssr.js'
```

**Comment by YitzhakAndrade** [comment]
I have the same problem here. This last answer didn't resolve.

**Comment by euvl** [comment]
@YitzhakAndrade so debug it 👍

**Comment by YitzhakAndrade** [comment]
Isn't there something like https://github.com/Stabzs/vue-on-toast#popping-a-toast-outside-of-a-vue-instance ?

**Comment by YitzhakAndrade** [comment]
For me, to pop a notification from an custom axios plugin (middleware).

```
$axios.onResponse(response => {
    notifier.$notify({
      title: 'Title',
      type: 'success'
    });
  });
```

**Comment by euvl** [comment]
Yes, you can do `Vue.notify(...)`

**Comment by YitzhakAndrade** [comment]
TypeError: __WEBPACK_IMPORTED_MODULE_2_vue__.default.notify is not a function

**Comment by toadkicker** [comment]
Did you import Vue?

**Comment by toadkicker** [comment]
TBH I've not done this way because I've found global style error catching like this is not a great user experience. I handle this in my vuex actions when calling axios, or on the page level. Calling $notify from a plugin probably doesn't work because $notify is a plugin and hasn't been initialized yet.

**Comment by tiagomatosweb** [comment]
I ended up importing Vue and using Vue.notify(...).

**Comment by Tchoupinax** [comment]
Any update about this problem ?
I have this issue, following the documentation

![image](https://user-images.githubusercontent.com/9136206/67156205-e26d6f00-f31b-11e9-9936-b8b1bd8c4ded.png)

And i tried `Vue.notify(...)` but i had the same Webpack error : `default.notify is not a function`

**Comment by Jonarod** [comment]
Struggled a bit too. I finally did this way:

```
// in ~/plugins/notifications.js

import Vue from 'vue'
import Notifications from 'vue-notification'
Vue.use(Notifications)

export default (context, inject) => {
  inject('notify', Vue.notify)
}
```

then anywhere in components/pages...

```
this.$notify({ group: 'all', text: 'Heyy !!!' })
```

**Comment by scratchmex** [comment]
This should be added to the docs. @euvl I suggest reopening

**Comment by lightmyfire17** [comment]
Agree, also found @Jonarod solution useful.

**Comment by Bullettoothtobi** [comment]
Thanks @Jonarod for your solution. I adjusted it a little bit and this works for me:

**Plugins**

notify.client.js

```
import Vue           from 'vue'
import Notifications from 'vue-notification'

Vue.use(Notifications)
```

notify.server.js

```
import Vue           from 'vue'
import Notifications from 'vue-notification/dist/ssr.js'

Vue.use(Notifications)
```

**Config**

nuxt.config.js
```
...
plugins: [
    { src: '~plugins/notify.client', mode: 'client' },
    { src: '~plugins/notify.server', mode: 'server' },
 ],
...
```

**Layout**

layouts/default.vue
```
...
<notifications group="all" />
...
```

**Notification**

somewhere
```
...
this.$notify({ group: 'all', text: 'Heyy !!!' })
...
```

**Comment by andrejsharapov** [comment]
@Bullettoothtobi, how do you deal with styles with SSR? And repeated button presses?

**Comment by Venegrad** [comment]
How i can use it from Store?

**Comment by ZackNew** [comment]
i'm in exactly the same position with the question, and all the solutions are not working for me, is there any update to your situation? @iam-mishgun

**Comment by iam-mishgun** [comment]
> i'm in exactly the same position with the question, and all the solutions are not working for me, is there any update to your situation? @iam-mishgun

dont use this package) 
its died
