### ISSUE TITLE
Dynamic instance Name

### ISSUE THREAD

**Issue by alphaelf** [euvl/vue-notification#85]
hi,
i use element-ui that register `$notify` in `Vue.prototype` can u provide name parameter to define instance name? like `Vue.use(Notification, {name: 'alert'})` so we can use it as `this.$alert({...})`

**Comment by jariesdev** [comment]
Same here, can you allow us to modify the instance name? I use element-ui which come with the same $notify instance and overwrites yours.

**Comment by jariesdev** [comment]
@euvl thanks, It working now.

**Comment by euvl** [comment]
published
