### ISSUE TITLE
Global method for calling notification outside vm

### ISSUE THREAD

**Issue by martiendt** [euvl/vue-notification#86]
Hi, currently i create  an internal plugin (wrapper) and make `vue-notification` as adapter. But i cannot use `this.$notify()` here, can you make `notify` as global function so i can call it like `Vue.notify()`

    export default {
      install: (Vue) => {
        Vue.prototype.$notification = {
          custom (options) {
            Vue.notify({
              group: 'notification',
              type: options.type,
              title: options.title,
              text: options.text
            })
          },
          info (text, title = '') {
            this.custom({text, title, type: 'info'})
          },
          success (text, title = '') {
            this.custom({text, title, type: 'success'})
          },
          warn (text, title = '') {
            this.custom({text, title, type: 'warn'})
          },
          error (text, title = '') {
            this.custom({text, title, type: 'error'})
          }
        }
      }
    }

**Comment by euvl** [comment]
Nice, published 1.3.12 👍 Well done
