### ISSUE TITLE
Issue in Custom template

### ISSUE THREAD

**Issue by AhmedMohsen0** [euvl/vue-notification#90]
I have an issue when i use the custom template the type property in notification object doesn't work.
The notifications appears white.
here 's my html code:
[https://ideone.com/zn5H0c](url)
here is the function that makes the notification object:
[https://ideone.com/CYWZUX](url)

 
![white-notification](https://user-images.githubusercontent.com/8531926/42689928-b35df694-86a2-11e8-8886-cf6542b9a97f.png)

**Comment by ryopark** [comment]
I got the same issue.  I am not sure the type property actually works with a custom template because I couldn't find any example of using both.

**Comment by euvl** [comment]
It does not, you need to implement types itself (its just css classes, so the plugin does not know how to style your custom component with custom classes, if it makes sense).
