### ISSUE TITLE
Question: Shown and Disappear Events

### ISSUE THREAD

**Issue by jariesdev** [euvl/vue-notification#94]
Does this have Events like when the notification is shown or hide?

**Comment by euvl** [comment]
Sounds good, feel free to play with it, i will be happy to review any PRs 😉

**Comment by wildstyles** [comment]
Oh, I am not so experienced developer :) Here I have found simple workaround:

Added in main.js
```
Vue.prototype.$notifyCb = ({ type, text, duration = 3000 }, cb) => {
  Vue.prototype.$notify({ type, text, duration });
  setTimeout(() => cb(), duration + 1000);
};
```

and then call it in component: 

`this.$notifyCb({ type: 'success', text: 'Erfolgreich Veränderte Konsequenz' }, () => { this.dialog = false; });`

**Comment by GitHub-Leon** [comment]
no event at click item or close item?

**Comment by jariesdev** [comment]
None by default but you can create an element with attached event like click on it user notification slot.

**Comment by i07** [comment]
It's a bit of a hack, but you can use velocity's enter and leave method. It accepts functions (see README.md), then use the data element to pass a function back into the component and execute it on leave or at enter.

`<notifications animation-type="velocity" :animation="animation"/>`

```
  animation: {
    enter(element) {
        let nData = this.$data.list[0].data;
        if (nData.onEnter) {
              nData.onEnter()
        }
        return {
           height: [element.clientHeight, 0],
        }
     },
     leave() {
        let nData = this.$data.list[0].data;
        if (nData.onClose) {
              nData.onClose()
        }
        return {
           height: 0,
           opacity: 0
        }
     }
  }
```

in your component:
```
$this.notify({
  group: 'foo',
  title: 'My Title',
  text: 'My Text',
  duration: 3000,
  data: {
    onEnter: () => { console.log('showing notification'); }
    onClose: () => { console.log('closing notification'); }
  }
});
```

**Comment by euvl** [comment]
Closing in favour of #152
